### ISSUE TITLE
Pendências iniciais

### ISSUE THREAD

**Issue by brunomontezano** [brunomontezano/predicting-functional-impairment#1]
@jfeiten @brunomontezano 

- [x]  Check-up inicial do script principal (estrutura, metodologia, etc)
- [x]  Adição de novo método de imputação (MICE ou caret::preProcess)
- [x]  Análise individual de _missing values_ "reais"

**Comment by jfeiten** [comment]
> @jfeiten @brunomontezano
> 
> * [x]   Check-up inicial do script principal (estrutura, metodologia, etc)
> * [x]   Adição de novo método de imputação (MICE ou caret::preProcess)
> * [x]   Análise individual de _missing values_ "reais"

**Comment by jfeiten** [comment]
Acho que seria melhor revisarmos juntos esta questão dos _missing values_.
